### ISSUE TITLE
Can't build for qemu-virt64-risv with RT-Thread 5.0.1

### ISSUE THREAD

**Issue by yf13** [mysterywolf/lwext4#24]
It seems that this package can't build with RT-Thread 5.0.1 for `qemu-virt64-riscv` target, using [this toolchain](https://download.rt-thread.org/rt-smart/riscv64/riscv64-linux-musleabi_for_x86_64-pc-linux-gnu_180881.tar.bz2).
For details, please see [this ticket](https://github.com/RT-Thread/userapps/issues/35).

**Comment by xqyjlj** [comment]
you can try this patch https://github.com/RT-Thread-packages/lwext4/pull/25
