### ISSUE TITLE
support RT-smart

### ISSUE THREAD

**Issue by unicornx** [mysterywolf/lwext4#26]
具体需求来源 see ：<https://github.com/RT-Thread/rt-thread/issues/9646>

**Comment by unicornx** [comment]
请问这个 ext4 的支持，是否和 bsp 有关，因为这个需求额发起实际上来自于 <https://github.com/RT-Thread/rt-thread/issues/9623#issuecomment-2472465702> ，这个测试是基于 qemu-virt64-riscv 开展的。

**Comment by BernardXiong** [comment]
这个是软件包，和bsp无关。主要是一份dfs v2.0的适配和对接

**Comment by polarvid** [comment]
- 代码树更新 https://github.com/RT-Thread-packages/lwext4/pull/27
- 索引树更新 https://github.com/RT-Thread/packages/pull/1827

**Comment by polarvid** [comment]
@unicornx 已更新，请知晓。谢谢。

**Comment by unicornx** [comment]
已经基于 rt-thread master c1166e0bf1 验证可以工作。

关闭此 issue。
